### ISSUE TITLE
11. Tests

### ISSUE THREAD

**Issue by ArtemChernikov** [ShamRail/job4j_requirements#1]
Не проходит по ссылке тесты:
![image](https://user-images.githubusercontent.com/96340711/217606070-a8e43ae1-e1c1-4430-89dc-76dac9e2a975.png)
![image](https://user-images.githubusercontent.com/96340711/217606176-947ca53a-4dc4-4101-ab33-d95a633b8d7e.png)

**Comment by ShamRail** [comment]
@ArtemChernikov спасибо. Исправил
